import Head from "next/head";
import Image from "next/image";
import Home from "../components/home/Home";

export default function Main() {
  return (
    <div>
      <Head>
        <title>Chaindustry</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </div>
  );
}
